# Topic is the highest level of organization. It serves as a container
# for datasets that should live together in their own schema.
name = "great_start_to_quality"
description = "The ETL script for loading the childcare information from GSTQ."

[tables.providers]
name="providers"
description = "The main GSTQ file that has every provider licensed in the state."
unit_of_analysis = "Childcare provider"
universe = "All childcare providers licensed in Michigan reported by GSTQ."
owner = "Great Start to Quality"
collector = "Great Start to Quality"
# collection_method = "Leave commented if not using"
collection_reason = "To help families select the right childcare program for their needs."
source_url = "https://greatstarttoquality.org/"
# notes = "Leave commented if not using"
# use_conditions = "Leave commented if not using"
cadence = "monthly"

# Variables are placed in their own sub-list with the table hierarchy
[[tables.providers.variables]]
name = "business_name"
description = "Licensed program name"

[[tables.providers.variables]]
name = "license_number"
description = "Unique identifier assigned to licensed facility"

[[tables.providers.variables]]
name = "contact_name"
description = "Person designated as a contact for the facility"

[[tables.providers.variables]]
name = "license_type"
description = "Type of licensed facility"

[[tables.providers.variables]]
name = "profile_link"
description = "A direct link to the program's profile page within the system"

# This variable exists in the raw file, but since it is all nulls currently, 
# I'm removing it from the table (MV)
# [[tables.providers.variables]]
# name = "referral_status_note"
# description = "Indicator used to designate program open/closure due to COVID"

[[tables.providers.variables]]
name = "phone"
description = "Program contact phone number"

[[tables.providers.variables]]
name = "email"
description = "Contact email address for program"

[[tables.providers.variables]]
name = "address"
description = "Physical street location of the facility"

[[tables.providers.variables]]
name = "city"
description = "Physical city location of the facility"

[[tables.providers.variables]]
name = "state"
description = "Physical state location of the facility"

[[tables.providers.variables]]
name = "zip_code"
description = "Zip code of physical location"

[[tables.providers.variables]]
name = "county"
description = "Physical county location of the facility"

[[tables.providers.variables]]
name = "region"
description = "Great Start to Quality designated region of the program"

[[tables.providers.variables]]
name = "isd_or_esa"
description = "State designated district of the program"

[[tables.providers.variables]]
name = "website"
description = "URL of program's website"

[[tables.providers.variables]]
name = "licensed_registered_date"
description = "Last license active date"

[[tables.providers.variables]]
name = "accepts_ages_from"
description = "Youngest age the program is currently enrolling"

[[tables.providers.variables]]
name = "accepts_ages_to"
description = "Oldest age the program is currently enrolling"

[[tables.providers.variables]]
name = "licensed_ages_from"
description = "Youngest age the program is currently licensed to serve"

[[tables.providers.variables]]
name = "licensed_ages_to"
description = "Oldest age the program is currently licensed to serve"

[[tables.providers.variables]]
name = "capacity"
description = "Licensed program capacity"

[[tables.providers.variables]]
name = "accreditation"
description = """Indicates program's participation in national early care and education accrediting body
NAC=National Accreditation Commission
NAEYC=National Association for the Education of Young Children
NAFCC=National Association for Family Child Care"""

[[tables.providers.variables]]
name = "full_time"
description = "Offers full-day care"

[[tables.providers.variables]]
name = "part_time"
description = "Offers care for 5 hours or less"

[[tables.providers.variables]]
name = "dropin_hourly"
description = "Offers back-up care on an as needed basis or care by the hour"

[[tables.providers.variables]]
name = "before_school"
description = "Offers schoolage care before regular school hours"

[[tables.providers.variables]]
name = "after_school"
description = "Offers schoolage care after regular school hours"

[[tables.providers.variables]]
name = "evening"
description = "Offers care after 5pm"

[[tables.providers.variables]]
name = "overnight"
description = "Offers care after 5pm"

[[tables.providers.variables]]
name = "all_hours"
description = "Offers care continuously"

[[tables.providers.variables]]
name = "weekend"
description = "Offers care on Saturdays and/or Sundays"

[[tables.providers.variables]]
name = "cdc_scholarships"
description = "Accepts Child Development and Care eligible families"

[[tables.providers.variables]]
name = "quality_level"
description = "Indicates the level of quality as defined by the GSQ quality improvement process"

[[tables.providers.variables]]
name = "publish_level_date"
description = "Date on which the program achieved the current quality level"

[[tables.providers.variables]]
name = "level_expiration_date"
description = "Date on which the current quality level expires"

[[tables.providers.variables]]
name = "cooperative"
description = "Program runs a cooperative model where parents support providing care"

[[tables.providers.variables]]
name = "faith_based"
description = "Program has a religious affiliation or inspired curriculum"

[[tables.providers.variables]]
name = "montessori"
description = "Program follows the Montessori curriculum and philosophy"

[[tables.providers.variables]]
name = "reggio_inspired"
description = "Program follow the Reggio teaching philosophy"

[[tables.providers.variables]]
name = "preschool"
description = "Program offers a preschool program"

[[tables.providers.variables]]
name = "strong_beginnings"
description = ""

[[tables.providers.variables]]
name = "gsrp"
description = "Program offers a Michigan's state funded Pre-K program"

[[tables.providers.variables]]
name = "early_head_start"
description = "Program offers a federally funded Early Head Start Program for ages birth to age 3"

[[tables.providers.variables]]
name = "head_start"
description = "Program offers a federally funded Head Start Program for ages 3-5"

[[tables.providers.variables]]
name = "school_age"
description = "Program offers only schoolage care, including before and after school or care during school break and summer"

[[tables.providers.variables]]
name = "nature_based"
description = ""

# Editions tracks when items were uploaded.
[tables.providers.editions.2025-01-01]
edition_date = "2025-01-01"
notes = "First upload of this dataset"
raw_path = "V:/DATA/Childcare/Great start to quality/Data/2025_Jan/Raw/gstq_2025_Jan.xlsx"

start = "2025-01-01" 
end = "2025-01-31" # Not used on rows

published = "2025-01-01"
acquired = "2025-01-08" 


[tables.providers.editions.2024-10-01]
edition_date = "2024-10-01"
notes = """This is the first table uploaded using the new schema reported by GSTQ.
'school_age' is not available on this dataset but is available on subsequent datasets."""
raw_path = "V:/DATA/Childcare/Great start to quality/Data/2024_Q4/Raw/gstq_2024_Q4.xlsx"

start = "2024-10-01" 
end = "2024-12-31" # Not used on rows

published = "2024-10-21"
acquired = "2024-10-21" 


[tables.providers.editions.2024-07-01]
edition_date = "2024-07-01"
notes = """This is the first table uploaded using the new schema reported by GSTQ.
'school_age' is not available on this dataset but is available on subsequent datasets."""
raw_path = "V:/DATA/Childcare/Great start to quality/Data/2024_Q3/Raw/gstq_2024_Q3.xlsx"

start = "2024-07-01" 
end = "2024-09-30" # Not used on rows

published = "2024-07-01"
acquired = "2024-07-01" 


[tables.providers.editions.2024-04-01]
edition_date = "2024-04-01"
notes = ""
raw_path = "V:/DATA/Childcare/Great start to quality/Data/2024_Q2/Raw/gstq_2024_Q2.xlsx"

start = "2024-04-01" 
end = "2024-06-30" # Not used on rows

published = "2024-04-08"
acquired = "2024-04-08" 


[tables.providers.editions.2024-01-01]
edition_date = "2024-01-01"
notes = ""
raw_path = "V:/DATA/Childcare/Great start to quality/Data/2023/Raw/gstq_2023.xlsx"

start = "2024-01-01" 
end = "2024-03-30" # Not used on rows

published = "2023-12-06"
acquired = "2023-12-06" 

