FIELD_NAME_UPDATE_2023 = {
    'Great Start Readiness Program': 'gsrp',
}

FIELD_NAME_UPDATE_2024 = {
    'Child Development and Care (CDC) Subsidy': 'Child Development and Care (CDC) Scholarships',
    'School Age ONLY': 'School-age',
}

FIELD_RENAME = {
    'Business Name': 'business_name',
    'License Number': 'license_number',
    'Contact Name': 'contact_name',
    'License Type': 'license_type',
    'Profile Link': 'profile_link',
    'Referral Status Note': 'referral_status_note',
    'Phone': 'phone',
    'Email': 'email',
    'Address': 'address',
    'City': 'city',
    'State': 'state',
    'Zip Code': 'zip_code',
    'County': 'county',
    'Region': 'region',
    'Intermediate School District (ISD) or Education Service Agency (ESA)': 'isd_or_esa',
    'Website': 'website',
    'Licensed/registered date': 'licensed_registered_date',
    'Accepts Ages From': 'accepts_from_mos',
    'Accepts Ages To': 'accepts_to_mos',
    'Licensed Ages From': 'licensed_from_mos',
    'Licensed Ages To': 'licensed_to_mos',
    'Capacity': 'capacity',
    'Accreditation': 'accreditation',
    'Full-Time': 'full_time',
    'Part-Time': 'part_time',
    'Drop-in/Hourly': 'dropin_hourly',
    'Before School': 'before_school',
    'After School': 'after_school',
    'Evening': 'evening',
    'Overnight': 'overnight',
    '24 Hours': 'all_hours',
    'Weekend': 'weekend',
    'Child Development and Care (CDC) Scholarships': 'cdc_scholarships',
    'Quality Level': 'quality_level',
    'Publish Level Date': 'publish_level_date',
    'Level Expiration Date': 'level_expiration_date',
    'Cooperative': 'cooperative',
    'Faith-based': 'faith_based',
    'Montessori': 'montessori',
    'Reggio Inspired': 'reggio_inspired',
    'Preschool': 'preschool',
    'Strong Beginnings': 'strong_beginnings',
    'GSRP-Great Start Readiness Program': 'gsrp',
    'Early Head Start': 'early_head_start',
    'Head Start': 'head_start',
    'School-age': 'school_age',
    'Nature-based': 'nature_based',
}

FIELD_REFERENCE = {val: key for key, val in FIELD_RENAME.items()}

